name = "orka_demo"
description = "Demo using Orka 3D engine"
version = "0.2.0"

authors = ["onox"]
maintainers = ["onox <denkpadje@gmail.com>"]
maintainers-logins = ["onox"]

executables = ["orka_demo"]

[build-switches]
validation.compile_checks = "warnings"
"*".style_checks = ["-gnatygAOM99-Is"]

[[depends-on]]
awt = "^1.0.0"
orka = "~0.2.0"
orka_plugin_atmosphere = "^1.0.0"
orka_plugin_terrain = "^1.0.0"

[[pins]]
awt = { path = "../orka/awt" }
orka = { path = "../orka/orka" }
orka_plugin_atmosphere = { path = "../orka/orka_plugin_atmosphere" }
orka_plugin_terrain = { path = "../orka/orka_plugin_terrain" }
